### ISSUE TITLE
Add docs.rs badge

### ISSUE THREAD

**Issue by Lucretiel** [Lucretiel/joinery#16]
Docs.rs/about

**Comment by Atul9** [comment]
@Lucretiel I found that joinery Readme contains docs.rs badge. What needs to be done in this issue?

**Comment by Lucretiel** [comment]
The one that's currently their is a custom shields.io badge; it doesn't auto-update the version. I want to replace it with the badge on https://docs.rs/about.

It's not a difficult issue, I just haven't gotten around to it.
